FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

#Copy everything
COPY ./Consumidor ./Consumidor
COPY ./Infrastructure ./Infrastructure
COPY ./Core ./Core

WORKDIR /App/Consumidor

#rESTORE AS DISTINCT LAYERS
RUN dotnet restore 
#Build and publish a release
RUN dotnet publish -c Release -o out

#EXPOR A PORTA PARA INTERNET
EXPOSE 44344

#Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App/Consumidor
COPY --from=build-env /App/Consumidor/out .
ENTRYPOINT ["dotnete", "DotNet.Docker.dll"]