apiVersion: v1
kind: Pod
metadata:
  name: fiap-sql-techchallange
  labels:
    app: fiap-sql-techchallange
spec:
  containers:
    #- name: masstransit-posbooks
    #  image: masstransit/rabbitmq
    #  ports:
    #    - containerPort: 5672
    #    - containerPort: 15672

    - name: sql
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - containerPort: 1433
      env:
        - name: "ACCEPT_EULA"
          value: "Y"
        - name: "MSSQL_SA_PASSWORD"
          value: "Passw0rd"
        - name: MSSQL_PID
          value: "Developer"


