apiVersion: v1
kind: Pod
metadata:
  name: fiap-techchallange
  labels:
    app: fiap-techchallange
spec:
  containers:
    #- name: masstransit-posbooks
    #  image: masstransit/rabbitmq
    #  ports:
    #    - containerPort: 5672
    #    - containerPort: 15672

    - name: sql
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports:
        - containerPort: 1433
      env:
        - name: "MSSQL_SA_PASSWORD"
          value: "Passw0rd"
        - name: "ACCEPT_EULA"
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
    - name: fiap-api
      image: fiap-contato-api:v1
      ports:
        - containerPort: 8080
      env:
        - name: "CONNECTIONSTRINGS__CONNECTIONSTRING"
        # scv-sql-techchallange 32200 ;Trust Server Certificate=True
          value: "Server=tcp:localhost;Database=TechChallangeCadastroCotatos;User ID=sa;Passw0rd;TrustServerCertificate=True;"
    
    


