apiVersion: v1
kind: Pod
metadata:
  name: fiap-consumidor-techchallange
  labels:
    app: fiap-consumidor-techchallange
spec:
  containers:
    - name: fiap-consumidor-techchallange
      image: fiap-consumidor:v1
      ports:
        - containerPort: 8080
      env:
        - name: "CONNECTIONSTRINGS__CONNECTIONSTRING"
          value: "Server=scv-sql-techchallange,1433;Database=TechChallangeCadastroCotatos;User ID=sa;Password=Passw0rd;TrustServerCertificate=True;"
        - name: "MassTransit__Servidor"
          value: "scv-menssageria-techchallange"
