apiVersion: v1
kind: Pod
metadata:
  name: fiap-api-techchallange
  labels:
    app: fiap-api-techchallange
spec:
  containers:
    - name: fiap-api-techchallange
      image: mayasilva/fiap-contato-api:latest
      ports:
        - containerPort: 8080