apiVersion: v1
kind: Service
metadata:
  name: scv-techchallange
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 31100
  selector:
    app: fiap-techchallange-consumidor