apiVersion: v1
kind: Service
metadata:
  name: scv-api-techchallange
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32100
  selector:
    app: fiap-api-techchallange